# Generated by Django 5.2 on 2025-04-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'verbose_name': 'Квартира', 'verbose_name_plural': 'Квартири'},
        ),
        migrations.AlterField(
            model_name='apartment',
            name='status',
            field=models.CharField(choices=[('approved', 'Підтверджено'), ('pending', 'Очікує'), ('rejected', 'Відмовлено')], default='pending', max_length=20),
        ),
    ]
